### ISSUE TITLE
Admin::url is not using standard url helpers ?

### ISSUE THREAD

**Issue by isometriq** [z-song/laravel-admin#992]
I had issues because of this in the Admin facade
```
    public static function url($url)
    {
        $prefix = (string) config('admin.prefix');

        if (empty($prefix) || $prefix == '/') {
            return '/'.trim($url, '/');
        }

        return "/$prefix/".trim($url, '/');
    }
```
Why isn't the `url` laravel helper used? like this
```
return url("/$prefix/".trim($url, '/'));
```
The problem is that laravel creates absolute urls and that's what I need. An example was the login form in the form tag.

**Comment by isometriq** [comment]
Because of this issue, deployment cases where laravel is installed inside a subfolder or a virtual document root, will cause the admin to not work at all.

The snippet suggested is my guess, but maybe there is a better place for fixing...

**Comment by mendieta** [comment]
Has anyone find a way to fix this?

**Comment by isometriq** [comment]
I think it's possible by overriding some classes, but involves digging deep in the source. It would make sense that the package is adjusted. I think it's a matter of replacing `Admin::url()` calls in the all the views.

I've tried overriding the `Admin` class, but the url method seems to be used internally too. So changing that there is breaking something else.

**Comment by z-song** [comment]
fixed in version 1.5

**Comment by bakrianoo** [comment]
Could any one help me to install the library in a sub-directory on a shared hosting in easy steps. The problem that after I entered the login credentials, I redirected to 
`URL/admin/auth/login`
but the correct path could be:
`URL/subdir/public/admin/auth/login`
=========
I am using version 1.5 + laravel 5.5

**Comment by harryxu** [comment]
@bakrianoo I have the same problem.

**Comment by s6carlo** [comment]
@omidakhavan  Thanks for login/header/menu fixing, the problem is that the issue remain for all actions.

For example in grid show / delete / edit have the wrong url.

The same for new / export button.. 

I have this situation in a testing environment and for now I fixed it by .htaccess in main web server root root
```
RewriteEngine On
RewriteRule ^admin/(.*)$ /subdir/public/admin/$1 [R=301,NC,L]

```

**Comment by bthiban** [comment]
`url(admin_base_path('/'))` replace all `admin_base_path`
